apiVersion: v1
kind: ConfigMap
metadata:
  name: integration-service-api-config
data:
  PORT: "3000"
  API_VERSION: v1
  DATABASE_NAME: admin
  NETWORK: main
  EXPLORER: https://explorer.iota.org/mainnet/transaction
  IOTA_PERMA_NODE: https://chrysalis-chronicle.iota.org/api/mainnet/
  DATABASE_URL: mongodb://username:password@mongodb-service.default.svc.cluster.local:27017/test?authSource=admin&readPreference=primary&appname=integration-service-api&ssl=false
  IOTA_HORNET_NODE: http://hornet-tcp.default.svc.cluster.local:14265
  SERVER_IDENTITY: did:iota:9AcqKU9EtDLpthr1umen9BTfxCWAjpTU4SSiexiwnTCr
