--- # ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: integration-service-pvc
# spec:
#   resources:
#     requests:
#       storage: 1Gi
#   accessModes:
#     - ReadWriteOnce
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: root-identity-pvc
spec:
  resources:
    requests:
      storage: 10Mi
  accessModes:
    - ReadWriteOnce
