version: '3.7'
services:
  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_DATABASE: ${DATABASE_NAME}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
  ensuresec_api:
    build: .
    environment: 
      PORT: 3000
      DATABASE_NAME: ${DATABASE_NAME}
      IOTA_HORNET_NODE: ${IOTA_HORNET_NODE}
      IOTA_PERMA_NODE: ${IOTA_PERMA_NODE}
      DATABASE_URL: ${DATABASE_URL}
      SERVER_SECRET: ${SERVER_SECRET}
    depends_on: 
      - mongodb_container
    ports:
      - 3000:3000
volumes:
  mongodb_data_container:
